### PR TITLE
Ci: Major code re-organization and CI templates update.

### PR DESCRIPTION
**Pull request by leamas**
Second try, this time against the master branch...

This is sort of an invasive PR, with partly big changes without any meaningful intermediary steps. Sorry for that. Keynotes:

  - It is now possible to make local builds which creates tarballs which can be imported and tested using the "Import Plugin"  button See https://github.com/Rasbats/managed_plugins/wiki/Local-Build
  - The CircleCI and Appveyor builders should work as before, but please check the setup described in https://github.com/Rasbats/managed_plugins/wiki/CircleCI
  - Here is also support for making pull requests against the [plugins project](http://github.com/OpenCPN/plugins). This requires additional setup, see the [wiki](https://github.com/Rasbats/managed_plugins/wiki/OpenCPN-Plugins-Catalog-and-Github-Integration)
  - The Travis service has been replaced by drone.io. One needs to set up this, see https://github.com/Rasbats/managed_plugins/wiki/Drone. The background is that Travis is no longer free, see discussion in https://github.com/OpenCPN/OpenCPN/issues/2178
  - The code has been re-organized into separate libraries to fit the overall design. It's of limited value since everything basically includes everything.
  - The administration of new releases in CMakeLists.txt have changed, but should be pretty self-explanatory.:

I have *ŃOT* tested anything, leaving this for others -- this took more time than I anticipated. 

Build logs: [Circle CI](https://app.circleci.com/pipelines/github/leamas/radar_pi/93/workflows/1dbe61a0-2180-496d-8c4a-6c2db2ae5eca), [Appveyor](https://ci.appveyor.com/project/leamas/radar-pi/builds/38155823) and [drone](https://cloud.drone.io/leamas/radar_pi/19)

### CODE REVIEW

**Comment by leamas** [comment]
The commit builds above broke when I closed the previous PR which was against wrong branch. See logs above for proper results.

**Comment by keesverruijt** [comment]
I'm doing a manual merge.

Any reason you put the plugin source code for the radar-specific code in subdirs of `libs/` instead of subdirs of `src/`?

**Comment by leamas** [comment]
The genaraö idea is that general-purpose things like wxJSON is better off in  as separate libs. This means that they are easy to maintain, replace and share between plugins. When I did this, I after a while understood the dependencies which are (hm) interesting...

Anyway, in hindsight I would probably not done it this this way, it was too much work. OTOH, there is now smaller parts which , after cleaning up dependencies, should be easier to maintain. Or, it could be reverted.....

**Comment by leamas** [comment]
Added the pre-release tag stuff + a missing file for manual builds. Nice to see all relevant builds kick in when I do so.

**Comment by keesverruijt** [comment]
The checks showing up is very nice indeed. Super.

**Pull request merged**
