### PR TITLE
Plugin loader fixes, ci builds and some cleanup.

### PR DESCRIPTION
**Pull request by leamas**
This series basically makes the plugin usable as a downloadable artifact in https://github.com/OpenCPN/OpenCPN/pull/1457. It provides:

  - Some basic cleanup of the msvc API handling.
  - Fixes to use the new API supporting relocatable data directories.
  - Generation of .tar.gz tarballs and XML metadata
  - Fixes to make plugin build on mingw and flatpak.
  - ci-scripts supporting travis and circleci builders deployed to bintray.com and/or cloudsmith.io.

It should *not* affect the current installable package generation. It should be straight-forward to add these to the deployement scripts, though.

### CODE REVIEW

**Comment by keesverruijt** [comment]
Wow, this is a lot to digest. Let me check that it doesn't mess with our current travis / appveyor integration.

**Comment by leamas** [comment]
Yes.... looking at it again I think I have been a little sloppy with the CI scripts. Here is also a little too much duplication, you could compare with corresponding PR https://github.com/OpenCPN/OpenCPN/pull/1457 which I have worked a little more with.

The deployment will not work without a CLOUDSMITH_API_KEY.  In the long run we need a common playground on cloudsmith (or somewhere else, bintray?). But if you just want to test I can send you the key in a PM, just contact me on  leamas dot alec AT gmail.

**Comment by rgleason** [comment]
It would be very much appreciated by windows users,  if the windows installer.exe files were still made, for the time being, until all users get updated with the new version of O that has the plugin installer. BTW (I don't think the file needs to be part of the plugin install "stream", just must have the ability in the repository to build appveyor windows install.exe  and it the gets deployed as it currently gets deployed.

**Comment by leamas** [comment]
IIRC, the .exe packages are still built. It's just that I don't deploy them. We have an off-bug conversation on this issue for now, please stay tuned.

**Comment by leamas** [comment]
Some forced pushes to trigger circleci builds, there was some kind of intermittent error. Just commit comments changes to the tip.

Now, the .travis.yml is restored to upstream/master [13c228fb]  so this  PR does not mess with that file which looks self-contained (as opposed to the circleci setup using scripts in ci/). The plugin installer artifacts has been uploaded  to https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/.

To get the circleci pipeline running you need to create a circleci account and start following "your" project. This is straight-forward besides the macos builder which requires a manual request. I have had some contact with them on those issues; they have been extremely helpful  (and fast!) despite my free account.

You will also need a repo where things can be published. I can send my cloudsmith API key as a starter, but in the long run you will need your own repository on cloudsmith or elsewhere. Anything will  do as long as you reflect the changes in ci/circleci-upload.sh and radar-plugin.xml.in.

**Comment by leamas** [comment]
Now, we still have ti actually merge appveyor.yml. Stay tuned...

**Comment by leamas** [comment]
The appveyor upload *looks* OK, but judging if it really is is above my paygrade. Leaving this for now until there is more input.

**Comment by Hakansv** [comment]
@leamas 
So I've built for Win by VS2017 to my local repository only. No problem and runs as it should. 
Is there anything specific to verify?
Håkan

**Comment by leamas** [comment]
The important point is that the traditional NSIS .exe installer works as it always have, that this PR doesn't break it. As long as this is true it should IMHO be safe to merge it.

**Comment by Hakansv** [comment]
@leamas 
Yes both
radar_pi-5.0.4-P-load-1_msvc-10.0.17134.exe
and
radar_pi-5.0.4-P-load-1_msvc-10.0.17134.tar.gz
was created. The (exe) installer package works fine and no obstacles executing the plugin.
The plugin uninstall button is of course still not functional.
Håkan

**Comment by leamas** [comment]
OK & thanks!

I see that you and @keesverruijt  are the plugin maintainers.  Please let me know if there is anything I can do to make it possible to merge this PR.

**Comment by Hakansv** [comment]
Alec..
Yes Kees is the main programmer for the present code. Douwe is a mathematician and programmer. I may be called facilitator and tester so the main decision to include this PR may be up to Kees. 
For me the general goal for this PR on radar_pi is not yet clear. I suppose to announce a path for latest release to OCPN plugin loader. In that case some rules needs to be set. Is a pre-release or only a release viewable for the plugin loader. Should data for each plugin be kept at opencpn.org or another common location to by-pass the upload to OCPN download page and to make new PPA for Linux? Or are my questions out of scope?
Håkan

**Comment by leamas** [comment]
> I I suppose to announce a path for latest release to OCPN plugin loader. 

It is actually a circular dependency: if/when https://github.com/OpenCPN/OpenCPN/pull/1457 is merged, this PR represents an attractive way to install this plugin. But to merge  the opencpn PR it needs to be verified using a small set of plugins. In particular, we need to verify that the process to make plugins available in the installer is feasible.

> I suppose to announce a path for latest release to OCPN plugin loader

As things are now, the main program has a fixed set of plugin versions available defined by ocpn-plugins.xml. This version level should probably represent a well-known and tested version, perhaps not latest.

>  Should data for each plugin be kept at opencpn.org or another common location

There is really no need for that from the perspective of the opencpn and radar_pi PR:s.It is sufficient if  plugins can be downloaded from known URL:s.

> Or are my questions out of scope?

If it belongs in a PR it is IMHO in https://github.com/OpenCPN/OpenCPN/pull/1457. OTOH, I tend to think that these issues could and should be handled after merging this one. I think the basic structure is sound, basically based on a centrally maintained plugin catalogue.

That said, your point about how hard it is to regenerate this catalogue from sources  needs to be fixed. Such a fix should make it possible for at least "power users" to make new plugin /(versions) available.

**Comment by leamas** [comment]
@Hakansv 
> That said, your point about how hard it is to regenerate this catalogue from sources needs to be fixed

A fix has been added to OpenCPN/OpenCPN#1457, see  updated initial comment.

**Comment by leamas** [comment]
As I understand it this PR will not be merged during the beta cycle. Just to not forget things: expanding on the steps to activate building/deployment if/when it becomes actual:

**Building** works more or less out of the box after:
  - Open a (free) open-source account on circleci.com
  - Start following this project on circleci.
  - Start building in circleci, or just push a commit.

**Deployment**. The shipped configuration uses cloudsmith.io. This is not a requirement in any way, but this is how to get the shipped setup working:
  - Open an account on cloudsmith.io
  - Don't get alarmed when it looks like they want money. Open-source repos are free.
  - Create a repository for the binaries built on circleci.
  - Make a manual upload of a test file to the new repository using the web UI.
  - The cloudsmith web UI has a CLOUDSMITH_API_KEY variable available. In the 
    circleci web UI make this a available as an environment variable.
  - Review the ci/circleci-upload.sh, update repository and user.
  - Review the ci/appveyor-upload.sh, update repository and user.
  - Update  PKG_BASE_URL in CMakeLists.txt to reflect the base, download cloudsmith address (the uploaded test file can be useful here...)

If I got it right, every new build should after this push xml files + binary tarballs (debian, windows, macos, flatpak) to the cloudsmith repo

**Comment by leamas** [comment]
Added some new commits focused on deployment and builds. Fixes some build-image related build errors and makes it possible to direct tagged commits to one directory (typically the stable one) whereas other builds goes to a test directory.

Also: Add some metadata to the build artifacts to facilitate a better manual overview of the cloudsmith repor.

**Comment by leamas** [comment]
MOre updates to the tarball URL logic, tagged last foreked build ta have it available as a stable one.

**Comment by keesverruijt** [comment]
I think this PR is obsolete now that Dave has helped us create the 'ci' branch which works fine according to him. Agree @leamas?

**Comment by leamas** [comment]
Agreed!

**Pull request closed without merging**
