### PR TITLE
More efficient AIS-ARPA check.

### PR DESCRIPTION
**Pull request by Hakansv**
Maybe a way to save CPU when ARPA is not used?
And less digits in ARPA target name, four to two.

### CODE REVIEW

**Comment by douwefokkema** [comment]
Still two questions:
- 3 digits could be OK, but with 2 digits targets with identical id might be passed to O, creating confusion. But is there anything against 4 digits?
- targets detected inside the guard-zone can move anywhere outside the guard-zone. So I think only checking inside the guard-zone is not enough

**Comment by Hakansv** [comment]
Digits:
The command wxT("%2i" says: print at least the space for 2 digits. e.g. ARPA_1 / ARPA12 / ARPA123
With %4 it is  ARPA___1 / ARPA__12 / ARPA_123. (Underscore here to indicate spaces) Just to much spaces, I think. Nothing important but %2 looks better i.m.o.
Guard zone: 
Yes, that's what we've done so far. Actually we're searching a bit more, at least for an arc. AIS detection area is a square where the outer side is the guard zone(s) max outer limit.
But you're right. If the ARPA target moves outside that square it will not be hidden by an AIS as a MARPA set outside any guard zone. The latter would be clear, I think. If the user wants also a MARPA on the AIS target he knows what he's doing. But the first may be confusing as you say.
Would it be better to compare every AIS position to every ARPA position plus offset? I'm not sure for the moment how to do it but may be possible.
Thoughts:
What I do now is to collect only those AIS target covered by that square in a table. Then every time you update an ARPA target, and that's often, we compare against the table if there's any AIS in the neighborhood. 
I don't think we can collect every AIS. I could be thousands. 
?:> We could make the square bigger, but how big?
?:> Instead of the guard zone(s) outer limit we could use max range from own ship for any ARPA target. Such a value is easily updated every time you update ARPA to OCPN. Do you already know the range from own ship and can you add that to Class "Position"? Or we can calculate own ship range from the ARPA position and make a "Max" variable out of that.
?:> We could collect only those AIS inside canvas but that can also be thousands if zoomed far out.
?:> Or do you've better ideas?

**Comment by Hakansv** [comment]
Douwe..
I already have the range/distance on "my" side from pol->r.
This can be better. 
Or did you solve it before dinner? :-)  Now dinner for me i any case.

**Comment by Hakansv** [comment]
Thanks for pushing me to update the AIS selection logic. This will be better soon. 
I Discard this PR and make a new soon.

**Pull request closed without merging**
