### PR TITLE
Shipdriver CI templates update.

### PR DESCRIPTION
**Pull request by leamas**
Major update of the CI templates. An overview is available in  the [updated changelog](https://github.com/leamas/shipdriver_pi/blob/changelog/Changelog.md)

The bulk of the update is done using the update-templates script.

The work with the PR revealed an [OpenGL linkage bug](https://github.com/Rasbats/shipdriver_pi/issues/332) (again!), fixed in  one of the last commits.

### CODE REVIEW

**Comment by leamas** [comment]
CircleCI logs [here](https://app.circleci.com/pipelines/github/leamas/radar_pi/129/workflows/4b9c079f-8aba-4e0e-8b54-71d62c2f02c4)

**Comment by Hakansv** [comment]
@leamas 
Very nice! Although of radar topic but how can I apply the same on another plugin? The "updated changelog" link above is broken. I've also tried to follow the developer's manual but got stuck somewhere in the middle.
My attempts so far are here: [ais_vd_pi](https://github.com/Hakansv/ais-vd_pi)

**Comment by leamas** [comment]
@hakan

>  The "updated changelog" link above is broken

Right, it  pointed to merged PR. I updated link above, should now be OK

> how can I apply the same on another plugin

The basic tool is the _update_templates_ script and and related UPDATE_TEMPLATES.md document. Don't expect the result to be perfect, but it should be a good start.

Looking into this PR all the commits up to  4582361 was created by this script.

The large, manual job is to split CMakeLists.txt into Plugins.cmake and CMakeLists.txt. It should be possibly by looking at the examples here and in shipdriver. When done, use the CMakeLists.tx from shipdriver as-is.

The remaining work is  490efc3  .. 1e08aa4. These patches should be possible to apply as required. Most are probably not needed.
 
>  ais_vd_pi

I havn't really looked at it now. But if you need to discuss more please feel welcome to file a bug at your repo and send me  heads-up. Then

**Comment by Hakansv** [comment]
@leamas 
Thanks the builds was mostly fine using the template. Maybe we can continue here?: [ais-vd issue](https://github.com/Hakansv/ais-vd_pi/issues/1#issue-1071548531)

**Pull request merged**
