### PR TITLE
radar manual

### PR DESCRIPTION
**Pull request by oplaydo**
[skip ci] [skip appveyor]

Hope the skip stops any builds.

I am using the oplaydo account for the work on the plugins manual.

When the PR is accepted I will update the manual link to attach the build to the repo manual. 

A build from me is needed to update the demo manual at the moment.

### CODE REVIEW

**Comment by Hakansv** [comment]
@oplaydo @Rasbats 

I've seen parts of the conversation about this new manual management but I'm sorry to say I've not digest it in details.
Would you mind give a short instruction how to locally edit and the read the example you've uploaded? 
That's: 
Are there any tools used for text writing and adding pictures or do we just edit/add to the text files and copy picture files.? 
How can we check the result locally? I followed the mail demo link and it looks great but for future management a local viewer would be handy to see the result of an on going work.

Many thanks for the manual improvments
Håkan

**Comment by Rasbats** [comment]
This is a very tangled web but has a lot of possibilities, including internalisation of the manual and pdf production.

We are starting to document the tools needed but time!!!!!

* Reading the adoc files
Firefox and Chrome have an extension for reading the format: asciidoc. Called Asciidoctor.js Live Preview:
[https://github.com/asciidoctor/asciidoctor-chrome-extension/](https://github.com/asciidoctor/asciidoctor-chrome-extension/)

This allows a preview of the page as it would appear in HTML.

Updated plugins manual here:
[https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html](https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html)

Sorry about the change in naming. I did not like ocpn and user was not needed.

* Editing asciidoc
For minor edits a text editor can be used. Alec uses Vi. 
I use VS Code with the asciidoc extension (opensource Win, Lin, Mac).
Syntax for the markup:
[https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#ex-ul-max](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#ex-ul-max)

This is all going to take some time. I am working with plugin authors, so that their plugin manual is in their repo. This uses modules made from the OpenCPN dokuwiki.

**Comment by Hakansv** [comment]
@Rasbats 
Thanks I've started to study the work method and it looks promising so far. Amazing how a change in a document using VS Code is instantly detected in Firefox.
We may need some training to handle this but it would be doable. One short example is the right side link table box in your [test page](https://rasbats.github.io/ocpn-manuals-test/ocpn-user-plugins-manual/0.1/plugins.html) That one I haven't succeed to repeat here.

**Comment by Hakansv** [comment]
Mike
I can't get any pictures to show up in Firefox and couldn't find any clear answers. Any hints?

Select radar_pi and install a possible update. Click * Enable. *

image::radar_pi_enable.png[Enable plugin]

**Comment by Hakansv** [comment]
It turns out to be a pathway issue.
If I copy a picture to the /ROOT/pages/ directory the picture is found.
What's the correct way to use a relative path in the .adoc document? ( \ROOT\images)
Obviously is the auto generated link, see above post, not correct at least when working in Windows.

**Comment by oplaydo** [comment]
In Firefox set the images folder in the Asciidoctor.js extension.

firefox asciidoctor js

You could instead add an attribute to the top of the page to make it show:
:imagesdir: ../images/

I need to keep the images and pages in separate folders. If the images were in ROOT/assets/images I think Antora would find them by default but this adds too much complication to the structure IMHO.

These are early days. All this stuff needs adding to the opencpn-plugins-manual wiki. Your questions are helping me build this;)

**Comment by Hakansv** [comment]
Thanks. Both methods worked independently of each others. 
Discussion:
My first conclusion is it would be best to add the ":imagesdir: ../images/" attribute to the documents or preferably in some project header if present? 
The general Firefox Askiidoctor.js setting would affect all projects if a user happens to have more?

**Comment by Hakansv** [comment]
BTW: ref: https://docs.asciidoctor.org/asciidoc/latest/macros/images-directory/
"You only need to set it in your document header.!
But what's the "document header" in our case?

**Comment by oplaydo** [comment]
> "You only need to set it in your document header.!
But what's the "document header" in our case?

This is just text like :imagesdir at the top of the .adoc file. The text does not show on the webpage but it controls other stuff, which I have not investigated.

Agree: This is the best way of making the images show. Expecting people to find the option in Firefox may be too much. They just want to install the extension and click on the .adoc.

**Comment by oplaydo** [comment]
I will have a FAQ page on the opencpn-plugins-manual wiki. This will be the first FAQ!

It may be better to raise more questions at:
[https://github.com/Rasbats/opencpn-plugins-manual/issues](https://github.com/Rasbats/opencpn-plugins-manual/issues)

**Comment by Hakansv** [comment]
OIK, The document header is clear. I tough it maybe was referring to any "Project header" . But complete all documents with this is not at all a big issue of course.
Yes, a common location like your link is better for similar discussions. Thanks.

**Comment by Hakansv** [comment]
@keesverruijt   @douwefokkema 
My suggestion is we accept this PR?
I've local fork of this PR and my changes so far can be merged afterwards.
Håkan

**Comment by keesverruijt** [comment]
Ok go ahead

**Comment by Rasbats** [comment]
You are live on the manual website!
[https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html](https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html)
Top right of your pages you will see 'Edit this page'. Using this allows edits of the manual on Github. On the next build of your plugin the edits will be seen in the manual (after the main manual is updated).

Document title is not showing at the moment. Need to look at this.
Thanks Hakan for the edits already made.

BTW if you need HTML for a help button you will find it at:
[https://github.com/Rasbats/opencpn-plugins-manual/tree/main/docs/radar/0.1](https://github.com/Rasbats/opencpn-plugins-manual/tree/main/docs/radar/0.1)
This could be placed in a folder in your data directory and referenced by the plugin.

**Pull request merged**
